import type { RepoKey, StatusKey, TopologyRawNode } from "./types"
import { AlertTriangle, CircleDot, Loader2, Pause, type LucideIcon } from "lucide-react"

export const REPO_META: Record<
  RepoKey,
  { label: string; sub: string; accent: string; glow: string; border: string }
> = {
  "mind-id": {
    label: "MIND-ID",
    sub: "FRONTEND / COMMAND UI",
    accent: "#22d3ee",
    glow: "rgba(34,211,238,0.35)",
    border: "rgba(34,211,238,0.55)",
  },
  "mind-agent": {
    label: "MIND-AGENT",
    sub: "ORCHESTRATION / AI CORE",
    accent: "#a78bfa",
    glow: "rgba(167,139,250,0.35)",
    border: "rgba(167,139,250,0.55)",
  },
  "mindid-nocodb": {
    label: "NOCODB",
    sub: "DATA / CRM LAYER",
    accent: "#2dd4bf",
    glow: "rgba(45,212,191,0.35)",
    border: "rgba(45,212,191,0.55)",
  },
  customer_agent: {
    label: "CUSTOMER_AGENT",
    sub: "SALES / N8N PIPELINE",
    accent: "#fb923c",
    glow: "rgba(251,146,60,0.35)",
    border: "rgba(251,146,60,0.55)",
  },
}

export const ROOT_META = {
  label: "KOMUTA MERKEZI",
  sub: "ECOSYSTEM ROOT",
  accent: "#818cf8",
  glow: "rgba(129,140,248,0.4)",
  border: "rgba(129,140,248,0.6)",
}

export const STATUS_META: Record<
  StatusKey,
  { label: string; color: string; led: string; Icon: LucideIcon }
> = {
  calisir: { label: "ONLINE", color: "text-emerald-400", led: "#34d399", Icon: CircleDot },
  devam: { label: "SYNC", color: "text-amber-400", led: "#fbbf24", Icon: Loader2 },
  hata: { label: "FAULT", color: "text-rose-400", led: "#fb7185", Icon: AlertTriangle },
  pasif: { label: "STANDBY", color: "text-slate-400", led: "#94a3b8", Icon: Pause },
}

export const TOPOLOGY_NODES: TopologyRawNode[] = [
  {
    id: "mindid-anasayfa",
    repo: "mind-id",
    title: "Anasayfa",
    role: "Komuta Merkezi",
    description: "Tüm ekosistemin ana krokisi; canvas ve durum özeti.",
    type: "page",
    status: "calisir",
    collaboratesWith: ["mindid-agent", "mindid-aktif-gorevler", "mindid-istatistikler"],
  },
  {
    id: "mindid-agent",
    repo: "mind-id",
    title: "Agent Sayfası",
    role: "AI Asistan Paneli",
    description: "Ajanlarla sohbet ve görev gönderimi.",
    type: "page",
    status: "calisir",
    collaboratesWith: ["mindagent-orchestrator", "mindid-aktif-gorevler"],
  },
  {
    id: "mindid-aktif-gorevler",
    repo: "mind-id",
    title: "Aktif Görevler",
    role: "Görev Takip",
    description: "Çalışan ve tamamlanan işlerin listesi.",
    type: "page",
    status: "calisir",
    collaboratesWith: ["mindid-agent", "mindagent-orchestrator"],
  },
  {
    id: "mindid-isletmeler",
    repo: "mind-id",
    title: "İşletmeler",
    role: "Marka Yönetimi",
    description: "İşletme ve marka profilleri.",
    type: "page",
    status: "calisir",
    collaboratesWith: ["nocodb-crm-tables", "mindagent-marketing"],
  },
  {
    id: "mindid-istatistikler",
    repo: "mind-id",
    title: "İstatistikler",
    role: "Performans Paneli",
    description: "Metrik ve sonuç özeti.",
    type: "page",
    status: "calisir",
    collaboratesWith: ["mindid-aktif-gorevler", "nocodb-lead-database"],
  },
  {
    id: "mindid-ayarlar",
    repo: "mind-id",
    title: "Ayarlar",
    role: "Sistem Ayarları",
    description: "Profil, bildirim ve bağlantı ayarları.",
    type: "page",
    status: "calisir",
    collaboratesWith: [],
  },
  {
    id: "mindagent-orchestrator",
    repo: "mind-agent",
    title: "Orkestratör",
    role: "Görev Dağıtıcı",
    description: "İstekleri doğru ajana yönlendiren merkez.",
    type: "agent",
    status: "calisir",
    collaboratesWith: [
      "mindagent-image",
      "mindagent-video",
      "mindagent-marketing",
      "mindagent-analysis",
      "mindid-agent",
    ],
  },
  {
    id: "mindagent-image",
    repo: "mind-agent",
    title: "Görsel Ajan",
    role: "Image Gen",
    description: "Görsel üretim (Gemini).",
    type: "agent",
    status: "calisir",
    collaboratesWith: ["mindagent-orchestrator", "mindagent-marketing"],
  },
  {
    id: "mindagent-video",
    repo: "mind-agent",
    title: "Video Ajan",
    role: "Video Gen",
    description: "Video üretim (Veo, Kling, HeyGen).",
    type: "agent",
    status: "calisir",
    collaboratesWith: ["mindagent-orchestrator", "mindagent-marketing"],
  },
  {
    id: "mindagent-marketing",
    repo: "mind-agent",
    title: "Pazarlama Ajan",
    role: "Brand + Ads",
    description: "Marka ve reklam işleri.",
    type: "agent",
    status: "calisir",
    collaboratesWith: [
      "mindagent-orchestrator",
      "mindagent-image",
      "mindagent-video",
      "mindagent-analysis",
      "mindid-isletmeler",
      "customer-n8n-orchestrator",
    ],
  },
  {
    id: "mindagent-analysis",
    repo: "mind-agent",
    title: "Analiz Ajan",
    role: "Analytics",
    description: "Rapor ve performans yorumu.",
    type: "agent",
    status: "calisir",
    collaboratesWith: ["mindagent-orchestrator", "mindagent-marketing", "nocodb-lead-database"],
  },
  {
    id: "nocodb-lead-database",
    repo: "mindid-nocodb",
    title: "Lead DB",
    role: "Lead Deposu",
    description: "Potansiyel müşteri veritabanı.",
    type: "data",
    status: "calisir",
    collaboratesWith: [
      "nocodb-crm-tables",
      "customer-n8n-orchestrator",
      "mindid-istatistikler",
    ],
  },
  {
    id: "nocodb-crm-tables",
    repo: "mindid-nocodb",
    title: "CRM Tabloları",
    role: "CRM Kayıtları",
    description: "Müşteri ve işletme tabloları.",
    type: "data",
    status: "calisir",
    collaboratesWith: ["nocodb-lead-database", "mindid-isletmeler"],
  },
  {
    id: "customer-meta-lead",
    repo: "customer_agent",
    title: "Meta Lead",
    role: "Meta Ads",
    description: "Meta reklam lead toplama (pasif).",
    type: "agent",
    status: "pasif",
    collaboratesWith: ["customer-n8n-orchestrator", "nocodb-lead-database"],
  },
  {
    id: "customer-linkedin",
    repo: "customer_agent",
    title: "LinkedIn",
    role: "B2B Outreach",
    description: "LinkedIn avcısı (planlanan).",
    type: "agent",
    status: "hata",
    collaboratesWith: ["customer-n8n-orchestrator", "nocodb-lead-database"],
  },
  {
    id: "customer-clay-local",
    repo: "customer_agent",
    title: "Clay Local",
    role: "Enrichment",
    description: "Veri zenginleştirme (yapılacak).",
    type: "agent",
    status: "hata",
    collaboratesWith: ["customer-n8n-orchestrator", "nocodb-lead-database"],
  },
  {
    id: "customer-instagram-dm",
    repo: "customer_agent",
    title: "Instagram DM",
    role: "DM Bot",
    description: "DM otomasyonu (yapılacak).",
    type: "agent",
    status: "hata",
    collaboratesWith: ["customer-n8n-orchestrator", "nocodb-lead-database"],
  },
  {
    id: "customer-n8n-orchestrator",
    repo: "customer_agent",
    title: "n8n Orkestratör",
    role: "Sales Flow",
    description: "Satış ajanları iş akışı merkezi.",
    type: "workflow",
    status: "devam",
    collaboratesWith: [
      "customer-meta-lead",
      "customer-linkedin",
      "customer-clay-local",
      "customer-instagram-dm",
      "customer-mindagent-sdk",
      "nocodb-lead-database",
    ],
  },
  {
    id: "customer-mindagent-sdk",
    repo: "customer_agent",
    title: "Mind-Agent SDK",
    role: "Bridge",
    description: "customer_agent ↔ mind-agent köprüsü.",
    type: "integration",
    status: "devam",
    collaboratesWith: [
      "customer-n8n-orchestrator",
      "mindagent-orchestrator",
      "mindagent-marketing",
    ],
  },
]
